### ISSUE TITLE
Submission review

### ISSUE THREAD

**Issue by ivan-adakerja** [alfiyansyahhh/Bot-Messenger#1]
Hi Alfiyansyah! I am Ivan from AdaKerja :wave:
Thank you for your submission, here I have some comments and todo below

Reviews

[+] clear readme and setup tutorial
[+] code clean lint
[+] use database - mysql
[-] commit message can be more clearer
[-] no separation between dependencies and devDependencies
[-] folder structure / layering can be improved
[-] repeated code (ex. here on [respon.js](https://github.com/alfiyansyahhh/Bot-Messenger/blob/master/src/helpers/respon.js#L12-L44)). related on `respon.js`, unfamiliar error code `100 10`
[+-] state is simple and easy using bottender. but it use `count` and `switch case`, it will be hard to track for long state / question. worst case, if user always say hi, the bot won't start at all
[-] no test
[+] birthday calculation correct

Questions

- why use try & promise catch here `controller.Action.js`?
- will the app crash if db not connected? and why?
- can you improve your submission especially adding proper test?

What do you say?

**Comment by ashwintiwari88** [comment]
@alfiyansyahhh  , we look forward to your response

**Comment by alfiyansyahhh** [comment]
Hello Mr Ivan. Thanks for the review, sorry I'm slow to respond.

ok I will immediately answer questions 1-3 in sequence

1. i use try & catch promise here controller.Action.js to handle error generated from model.Action.js

2. the application will crash if the db is not connected, because all conditions other than hi to be precise in action.js and model.action.js are connected to the database. the flow is like this. action will call model then model will run database query and each query will call database link via config.js.
config.js will connect to the database via config env. and if env is empty or database is not connected then model can't send query and will send error response to controller and action will send error response (this is if user is running router like /messenger). and if the user sends a message other than hi, then the error is caused by the // save to mysql condition before the condition sends the response.

for this case "it will be hard to track for long state/question. worst case, if user always say hello, bot won't start at all" i purposely made it like that so no user named hi. but I'll fix it if it really looks bad.

3. i will try to fix it, but can you tell me , should i change the switch case to if else? or just adding test?

Thank you.

**Comment by alfiyansyahhh** [comment]
Hello Mr Ivan. Thanks for the review, sorry I'm slow to respond.

ok I will immediately answer questions 1-3 in sequence

1.  i use try & catch promise here controller.Action.js to handle error generated from model.Action.js

2.   application will continue to run if the db is not connected, but only until the user says hi, because all conditions other than hi precisely in action.js and model.action.js are connected to the database. the flow is like this. action will call model then model will run database query and each query will call database link via config.js.
config.js will connect to the database via config env. and if env is empty or database is not connected then model can't send query and will send error response to controller and action will send error response (this is if user is running router like /messenger). and if the user sends a message other than hi, then the error is caused by the // save to mysql condition before the condition sends the response.

 -  for this case "it will be hard to track for long state/question. worst case, if user always say hello, bot won't start at all" i 
   purposely made it like that so no user named hi. but I'll fix it if it really looks bad.

3.  i will try to fix it, but can you tell me , should i change the switch case to if else? (sorry for the error response on respon.js, it was my fault that was not careful)

**Comment by ivan-adakerja** [comment]
@alfiyansyahhh 

1. Don't you think the try & catch will be a waste? because you already have promise catch
2. Okayy
3. I mean if you combine using `count` as the state and `switch case` it will be hard to track. Imagine you have 20 questions, you wouldn't know which question is which unless you read them 1 by 1. So, would you change it?
```
switch (context.state.count) {
    case 0:
    case 1:
    ...
    case 19:
    case 20:
}
```

**Comment by alfiyansyahhh** [comment]
1. I think you are right, unless there are additional conditions. sorry I seem to be wrong, try catch in action to handle condition in action not model. model is handled with then catch. I have fixed it
3. oh i see ok, i can fix it.

**Comment by alfiyansyahhh** [comment]
I've fixed

**Comment by ivan-adakerja** [comment]
@alfiyansyahhh Thanks for the submission updates. 

Here's my last feedback

- Still see no improvement on test. here example on testing flow

```
// run with `npx jest`

const mockQuery = jest.fn()
jest.mock('mysql2', () => ({
  createConnection: () => ({
    connect: jest.fn(),
    query: mockQuery
  })
}))

const Action = require('./messenger/action.messenger');

describe('action.messenger.js', () => {
  describe('name flow', () => {
    const mockSendText = jest.fn()
    const mockSetState = jest.fn()

    beforeEach(async () => {
      await Action.Main({
        event: { text: 'Ivan' },
        state: { nama: '' },
        sendText: mockSendText,
        setState: mockSetState,
        session: { _state: {}, user: {} }
      })
    })

    it('should save state and data into messages', () => {
      expect(mockSetState).toHaveBeenCalledWith({ 
        nama: 'Ivan', 
        chat: 'Ivan' 
      })
      expect(mockQuery).toHaveBeenCalledTimes(1)
    })
    it('should send correct text', () => {
      expect(mockSendText).toHaveBeenCalledWith(
        'Hello Ivan, when is your birthday? Please answer in YYYY-MM-DD format.'
      )
    })
  })
})
```

---

- Here better state example

```
// helpers/constants.js
const STATES_ID = {
  ASK_NAME: 'ASK_NAME',
  ASK_BIRTHDAY: 'ASK_BIRTHDAY'
  ...
}

---

// messenger/action.messenger.js
const Action = {
  Main: async (context) => {
    const stateId = context.state.id;
    switch (stateId) {
      case STATES_ID.ASK_NAME:
        context.setState({id: STATES_ID.ASK_BIRTHDAY}) // set next state
        break
      case STATES_ID.ASK_BIRTHDAY:
    }
  }
}
```
